[package]
name = "cerium"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.12"
bytes = "1.10.1"

tokio = { version = "1.46.0", features = ["macros", "rt-multi-thread", "net", "time", "sync"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
macros = { path = "./macros" }
simdnbt = "0.7.1"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
bitflags = "2.9.1"
paste = "1.0.15"

rand = "0.9.1"
ureq = { version = "3.0.12", features = ["json"] }

# Logging
log = "0.4.27"
env_logger = "0.11.8"

# Encryption
aes = "0.8.4"
cfb8 = "0.8.1"
num-bigint = "0.4.6"
pkcs1 = "0.8.0-rc.2" # needed?
rsa = "=0.10.0-rc.1"
rsa-der = "0.3.0"
sha1 = "0.10.6"



